[general]
# For now this can only be a single directory, no
# subdirectories allowed!
out_dirname = "out"

# "blog" or "project"
mode = "project"

# If (header|footer)_filename is an empty string, no header
# or footer will be added to the rendered pages
header_filename = "header.html"
footer_filename = "footer.html"

external_links_target_blank = true

ignore = ["README.md"]

[blog]
posts_dirname = "post"
